receivers:
  otlp:
    protocols:
      grpc:
  prometheus:
      config:
        global:
          scrape_interval: 1m
          scrape_timeout: 10s
        scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 5s
            static_configs:
              - targets: ['0.0.0.0:8888']
          - job_name: "zookeeper"
            static_configs:
              - targets: ['zookeeper:1234'] 
                labels:
                  env: "dev"
            relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                regex: '([^:]+)(:[0-9]+)?'
                replacement: '${1}'
          - job_name: "kafka-broker"
            static_configs:
              - targets: ['broker:1234']  
                labels:
                  env: "dev"
            relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                regex: '([^:]+)(:[0-9]+)?'
                replacement: '${1}' 
          - job_name: "schema-registry"
            static_configs:
              - targets: ['schema-registry:1234']   
                labels:
                  env: "dev"
            relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                regex: '([^:]+)(:[0-9]+)?'
                replacement: '${1}' 
          - job_name: "kafka-connect"
            static_configs:
              - targets: ['connect:1234']   
                labels:
                  env: "dev"
                  kafka_connect_cluster_id: "cluster1"
            relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                regex: '([^:]+)(:[0-9]+)?'
                replacement: '${1}'
          - job_name: 'producer'
            static_configs:
              - targets: ['spring-app:1234', 'java-producer:1234']  
                labels:
                  env: 'dev' 
          - job_name: 'consumer'
            static_configs:
              - targets: ['java-consumer:1234']   
                labels:
                  env: 'dev' 
          - job_name: "kafka-lag-exporter"
            static_configs:
              - targets:
                  - "kafka-lag-exporter:9999"
                labels:
                  env: "dev"
            relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                regex: '([^:]+)(:[0-9]+)?'
                replacement: '${1}' 
          - job_name: 'spring'
            metrics_path:  '/actuator/prometheus'
            static_configs:
              - targets: ['spring-app:28080']   
                labels:
                  env: 'dev'

exporters: 

  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write

  logging:
    loglevel: debug

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger:14250 
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, jaeger]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]