spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          chuckProcessor-out-0:
            binder: kafka
            destination: chuck-scs-topic
            producer:
              useNativeEncoding: true
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.apache.kafka.common.serialization.StringSerializer
          chuckAvroProcessor-out-0:
            binder: kafka
            destination: chuck-scs-avro-topic
            producer:
              useNativeEncoding: true
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: http://localhost:8081
                auto.register.schemas: true