spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: broker:29092
        bindings:
          chuckProcessor-out-0:
            binder: kafka
            destination: chuck-scs-topic
            producer:
              useNativeEncoding: true
              configuration:
                client.id: chuck-scs-producer
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.apache.kafka.common.serialization.StringSerializer
                acks: all
          chuckAvroProcessor-out-0:
            binder: kafka
            destination: chuck-scs-avro-topic
            producer:
              useNativeEncoding: true
              configuration:
                client.id: chuck-scs-avro-producer
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                acks: all
                schema.registry.url: http://schema-registry:8081
                auto.register.schemas: true
