server:
  port: 18080
spring:
  jmx:
    enabled: true
  cloud:
    stream:
      function:
        definition: chuckProcessor;chuckAvroProcessor
      bindings:
        chuckProcessor-out-0:
          binder: kafka
          destination: chuck-scs-topic
          producer:
            useNativeEncoding: true
        chuckAvroProcessor-out-0:
          binder: kafka
          destination: chuck-scs-avro-topic
          producer:
            useNativeEncoding: true
      default-binder: kafka
management:
  endpoints:
    web:
      exposure:
        include: '*'