appPort: 38081
bootstrapServers: broker:29092
chuckClientId: chuck-java-consumer
chuckGroupId: chuck-java-cg
chuckTopic: chuck-java-topic
chuckAvroClientId: chuck-java-avro-consumer
chuckAvroTopic: chuck-java-avro-topic
schemaRegistryUrl: http://schema-registry:8081