spring:
  jmx:
    enabled: true
kafka:
  bootstrap-servers: localhost:9092
  chuck-client-id: chuck-producer
  chuck-topic: chuck-spring-topic
  chuck-avro-client-id: chuck-avro-producer
  chuck-avro-topic: chuck-spring-avro-topic
  schema-registry-url: http://localhost:8081